### ISSUE TITLE
game getting stuck on menu close with tbfix_073

### ISSUE THREAD

**Issue by Kaeltis** [Kaldaien/TBF#1]
I just uninstalled TBF, deleted all remaining configs and reinstalled it, now the game hangs (not responding except for music) as soon as I click on X to close the overlay menu, alt-tabbing also does not work, I can only close the game via the task manager.
There doesn't seem to be any useful information in the logs, if you still need them, let me know. :)

The versions before the new mouse fix (24eee14) worked without any problems.

Also, thank you so much for your awesome work on this :D

**Comment by Mistywing** [comment]
Confirming the existence of this issue on my end as well. [My Steam comment link.](http://steamcommunity.com/app/429660/discussions/0/142261352640205850/?ctp=110#c133256240733762716)

**Comment by Kaeltis** [comment]
Seems to be working again for me with tbfix_080 :)
