### ISSUE TITLE
CPY version capped at 45 FPS

### ISSUE THREAD

**Issue by XenosisReaper** [Kaldaien/TBF#5]
Seems a bit excessive tbh

**Comment by Kaldaien** [comment]
Yeah, far be it from me to call a pirate an idiot, but ... that fits.

You're aware that all of my previous mods don't even work with pirated copies? They're physically disabled.

I've actually lessened my restrictions on piracy. Go buy the game dumbass.

**Comment by XenosisReaper** [comment]
Your Zestiria fix works just fine on my cracked copy so I dunno what you're on about

Oh well, looks like somebody forked it already, cheers for the fix, sorry your principles got in the way of being a help to the community
