### ISSUE TITLE
Madness isn't working as intended

### ISSUE THREAD

**Issue by EloMaskedJusticiario** [Kaldaien/TBF#6]
We can't have that, how can i get my drama if the anti piracy stuff isn't working?

Fresh install of tbfix latest version on cpy version of the game, no 45 fps limit or anything, everything seems fine. It shouldn't be. Where's my bsod when i launch the game ? Cmon.

**Comment by Kaldaien** [comment]
You have a million different versions to choose form, stop being an idiot and continue using your old version.

**Comment by NightHammer1000** [comment]
This Kid is so funny. Also no Problem here. Everything works fine.
gr8 mod m8 i r8 8/8
